### ISSUE TITLE
前台，楼主是否需要做动态路径＋vue的组件来渲染C端用户界面

### ISSUE THREAD

**Issue by wwb568109135** [fireyy/vue-page-designer#1]
（1）在测试页面https://fireyy.github.io/vue-page-designer/
拿到的本地数据，JSON.parse(localStorage['vpd-data'])

（2）前台C端，楼主是否需要做动态路径＋vue的组件来渲染C端用户界面，技术选项，可以使用jq/vue 的技术栈

（3）作者 你的这个demo 有投产吗》？

**Comment by fireyy** [comment]
（1）你不一定需要保存到 `localStorage`, 在 `save` 方法里你可以调用后台接口进行保存
（2）前台看具体的项目里使用技术栈，可以是 Vue SPA 项目 或者 Vue SSR
（3）demo 没有投产，但是该项目被应用到一个后台系统中，
