### ISSUE TITLE
Now you can export JSON data. Why there is no export button

### ISSUE THREAD

**Issue by livelyPeng** [fireyy/vue-page-designer#17]

**Comment by fireyy** [comment]
https://github.com/fireyy/vue-page-designer#parameter-save

Use `save` event

**Comment by livelyPeng** [comment]
是中国人吗、我能加你QQ吗，

**Comment by livelyPeng** [comment]
It's easy to add a scroll bar. You don't have one

**Comment by livelyPeng** [comment]
How can I add a scroll bar，

**Comment by fireyy** [comment]
没明白你的意思，你再描述一下问题
