### ISSUE TITLE
使用交流

### ISSUE THREAD

**Issue by lingruibin** [fireyy/vue-page-designer#2]
地址：http://122.152.198.82:8000/pd/designer/index.html 。我在使用你的demo做个编辑器，希望能够得到帮助，一起完善这个小项目

**Comment by fireyy** [comment]
:) 具体有什么Bug 或者 功能建议可以直接在这里提出来

**Comment by idowe** [comment]
@lingruibin 您这个项目开源吗，很像微盟的
