### ISSUE TITLE
Locale 

### ISSUE THREAD

**Issue by dewbambs** [fireyy/vue-page-designer#27]
<template>
        <div>
            <h1>This is the best thing</h1>
            <vue-page-designer locale="en" />
        </div>
    </template>

    <script>
     export default {
    
      }
    </script>

Still the designer shows Chinese.

I'm using vue-cli 3, vue 2.6.11, vue-page-designer 1.0.1, vue-page-designer-widgets 0.1.4

**Comment by fireyy** [comment]
Use vue-page-designer 1.1.0
