### ISSUE TITLE
uploader、toast 组件会报错

### ISSUE THREAD

**Issue by biaochenxuying** [fireyy/vue-page-designer#3]
作者你好，install 了之后，按 start it quickly 的例子来用时，uploader、toast 组件会报错的，说没注册

**Comment by fireyy** [comment]
请描述一下使用过程，最好附带上报错截图，这样方便重现问题，谢谢

**Comment by wurui0922** [comment]
作者你好，你的这个demo真的很适合我现在的项目，但是我用起来有一些问题，希望作者可以看看我呀~~
### **问题描述**
install成功之后，再按照start it quicky 的例子，界面如下
![qq 20190119152445](https://user-images.githubusercontent.com/39662462/51423677-77610180-1bfe-11e9-816f-8ff3c8829253.png)

控制台报错如下
![1212123](https://user-images.githubusercontent.com/39662462/51423695-a1b2bf00-1bfe-11e9-8507-e990b53ff17f.png)

代码如下
![code](https://user-images.githubusercontent.com/39662462/51423722-20a7f780-1bff-11e9-8eed-5ee4e7ee6e92.png)

**Comment by fireyy** [comment]
@wurui0922 刚刚发布了 1.0.1 版本，你可以参照 README，应该没问题了
