### ISSUE TITLE
Translation in english

### ISSUE THREAD

**Issue by hubyhuby** [fireyy/vue-page-designer#7]
It is difficult to understand the demo if you are not speaking chinese. 
Translation to English would help

**Comment by fireyy** [comment]
I will add i18n later :)

**Comment by hubyhuby** [comment]
@fireyy 
Thanks for your answer. 
What I don t understand from the description of the project and the demo in chinese is the purpose of the project... 
For example can I export the vue code, once I did the design?

**Comment by biletskiy6** [comment]
How can i add Vue Router into this project?

**Comment by fireyy** [comment]
> How can i add Vue Router into this project?

It's a component, you can install and import it in your current project(which include vue-router)

**Comment by fireyy** [comment]
> @fireyy
> Thanks for your answer.
> What I don t understand from the description of the project and the demo in chinese is the purpose of the project...
> For example can I export the vue code, once I did the design?
> Or is the project outputting juste an image of the design?

It export json data now, but could export the vue code easily.

**Comment by livelyPeng** [comment]
Now you can export JSON data. Why there is no export button

**Comment by fireyy** [comment]
#19
